### ISSUE TITLE
Create PolKit rules for common dangerous commands

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/security#1]
Since we do not provide sudo in VOS2 and privileged operations must be performed with pkexec, we have the possibility to create policies that prevent the execution of dangerous commands, like `rm -rf /` and stuff like that.

**Comment by axtloss** [comment]
The required rules should be as simple as
```js
polkit.addRule(function(action, subject) {
    if (action.lookup("command") == "rm -rf /") {
        return polkit.Result.NO;
    }
});
```
However it would probably be smart to have some sort of program/script that generates these rules based on another file and also adds regex matching as `rm -rf /` may be blocked, but `rm -fr /` or `/usr/bin/rm -rf /` wouldn't get blocked

**Comment by mirkobrombin** [comment]
Now part of the hardening process. We are going for the interceptor way.
