### ISSUE TITLE
Enable fsguard in core,desktop,nvidia images

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/security#4]

**Comment by axtloss** [comment]
Resolved with

**Comment by axtloss** [comment]
Resolved with
- https://github.com/Vanilla-OS/desktop-image/pull/54
- https://github.com/Vanilla-OS/core-image/pull/23
- https://github.com/Vanilla-OS/nvidia-image/pull/14
- https://github.com/Vanilla-OS/vm-image/pull/4
